# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02b92342fe73a2c05f77e6988c48b7bbc21d93e5a98fb67db9896e809506c9e3e42d761aca6aaf23c53fce35b273e3086737ba5a4c28db23207bf4737daf2a04

test:
  secret_key_base: c9af5f5020b1236e75e0b42ec557db058891fcda9f6d57c6fbf106084b1c3d49ab0910924ee28eb84c268fdd470c61c1147f8d7b23f27800512053c9a3aa0ff9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
